SET DEFINE off;

CREATE OR REPLACE NONEDITIONABLE PROCEDURE "APP_LAB"."UPSET_INTITUICOES_ENSINO"(
    NOME_INTITUICAO VARCHAR2,
    ID_INSTITUICAO_ENSINO OUT INTEGER
) AS    v_count integer;
BEGIN
IF NOME_INTITUICAO IS NOT NULL THEN
    SELECT COUNT(*) INTO v_count FROM instituicoes_ensino WHERE ITE_NOME = NOME_INTITUICAO;
    IF v_count = 0 THEN
        INSERT INTO instituicoes_ensino (ITE_NOME) VALUES (NOME_INTITUICAO)
        RETURNING ITE_ID INTO ID_INSTITUICAO_ENSINO;
    ELSE
        SELECT ITE_ID INTO ID_INSTITUICAO_ENSINO FROM instituicoes_ensino WHERE ITE_NOME = NOME_INTITUICAO;
    END IF;
END IF;
END UPSET_INTITUICOES_ENSINO;