version: '3.1'
services:
  db:
    container_name: oracle-db-lab-banco
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    restart: "no"
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    networks:
      - labbanconetwork
  client:
    container_name: sql-developer-lab-banco
    build:
      context: .
      dockerfile: sql_developer/DockerFileSqlDeveloper
    environment:
      - USER_ORACLE=system
      - PASSWORD_ORACLE=Oracle_123
      - HOST_ORACLE=db
      - PORT_ORACLE=1521
      - SID=xe
      - DISPLAY=$DISPLAY
    restart: "no"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash /opt/sqldeveloper/sqldeveloper/sqldeveloper.sh 
    networks:
      - labbanconetwork
volumes:
  oracle-data:
  oracle-backup:
networks:
  labbanconetwork:
    driver: bridge