CREATE SEQUENCE "APP_AUDITORIA"."SEQ_AUD" MINVALUE 1 MAXVALUE  9999999999999999999999999999
INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOSCALE GLOBAL;


CREATE
OR REPLACE NONEDITIONABLE TRIGGER "APP_AUDITORIA"."TG_SEQ_AUD" BEFORE
INSERT
    ON AUDITORIA FOR EACH ROW BEGIN :NEW.aud_id := seq_aud.nextval;

END;